name: Publish

on:
  push:
    branches:
      - release

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - id: docker_build
        name: Build and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: c410f3r/toph-node:latest

      - env:
          SEED: ${{ secrets.SEED }}
        name: Publish
        uses: appleboy/ssh-action@master
        with:
          host: 35.192.47.173
          key: ${{ secrets.VM_PK }}
          passphrase: ${{ secrets.VM_PW }}
          script: |
            sudo apt update
            sudo apt install -y docker.io
            sudo docker stop toph-node-0 && sudo docker stop toph-node-1
            sudo docker rm toph-node-0 && sudo docker rm toph-node-1
            rm -rf $HOME/toph-node-0 $HOME/toph-node-1
            mkdir -p $HOME/toph-node-0 $HOME/toph-node-1

            AURA_PK="0x4c92dd81ab955d07b9c2e2068c76a0f91c44f4100593d8354df4b2d4ed4f7808"
            GRANDPA_PK="0xa14f866b8badbba40c8d36c8951e15bbaf6598d5e794d6f98711efd9f241e63b"

            COMMON_PARAMS="$PURGE_PARAMS --port 30333 --rpc-port 9933 --ws-port 9944"
            PURGE_PARAMS="--base-path /toph-node --chain testnet_joana"

            inject_keys() {
              local container=$1
              local aura_pk=$2
              local grandpa_pk=$3
              local seed=$4

              sleep 1

              DATA='{ "id":1, "jsonrpc":"2.0", "method":"author_insertKey", "params":["aura", "'"$seed"'", "'"$aura_pk"'"] }'
              CURL=$(echo "curl -H 'Content-Type: application/json' --data '$DATA' localhost:9933")

              sudo docker exec $container bash -c "$CURL"

              DATA='{ "id":1, "jsonrpc":"2.0", "method":"author_insertKey", "params":["gran", "'"$seed"'", "'"$grandpa_pk"'"] }'
              CURL=$(echo "curl -H 'Content-Type: application/json' --data '$DATA' localhost:9933")

              sudo docker exec $container bash -c "$CURL"

              sudo docker stop $container
              sudo docker rm $container
            }

            CONTAINER=$(sudo docker run -d -v $HOME/toph-node-1:/toph-node \
              c410f3r/toph-node $COMMON_PARAMS --name toph-node-1 --rpc-methods=Unsafe --validator
            )

            inject_keys "$CONTAINER" "$AURA_PK" "$GRANDPA_PK" "$SEED"

            sudo docker run \
              -d \
              --name toph-node-0 \
              -p 30333:30333 \
              -p 9933:9933 \
              -p 9944:9944 \
              --restart always \
              -v $HOME/toph-node-0:/toph-node \
              c410f3r/toph-node $COMMON_PARAMS --name toph-node-0 --rpc-external --ws-external

            sudo docker run \
              -d \
              --name toph-node-1 \
              -p 30334:30333 \
              -p 9934:9933 \
              -p 9945:9944 \
              --restart always \
              -v $HOME/toph-node-1:/toph-node \
              c410f3r/toph-node $COMMON_PARAMS --name toph-node-1 --validator
          username: toph-node
