name: Publish

on:
  push:
    branches:
      - release

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PW }}

      - name: Build and push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: c410f3r/toph-node:latest

      - name: Publish
        uses: appleboy/ssh-action@master
        with:
          host: 35.192.47.173
          key: ${{ secrets.VM_PK }}
          passphrase: ${{ secrets.VM_PW }}
          script: |
            sudo apt update
            sudo apt install -y docker.io
            sudo docker stop toph-node-0 && sudo docker stop toph-node-1
            sudo docker rm toph-node-0 && sudo docker rm toph-node-1
            mkdir -p $HOME/toph-node-0 $HOME/toph-node-1

            sudo docker run \
                -d \
                --name toph-node-0 \
                -p 30333:30333 \
                -p 9945:9944 \
                --restart on-failure \
                -v $HOME/toph-node-0:/toph-node \
                c410f3r/toph-node \
                    --base-path /toph-node \
                    --chain testnet_joana \
                    --name toph-node-0 \
                    --port 30333 \
                    --rpc-cors all \
                    --rpc-port 9933 \
                    --unsafe-ws-external \
                    --validator \
                    --ws-port 9944

            sudo docker run \
                -d \
                --name toph-node-1 \
                -p 30334:30333 \
                -p 9947:9944 \
                --restart on-failure \
                -v $HOME/toph-node-1:/toph-node \
                c410f3r/toph-node \
                    --base-path /toph-node \
                    --chain testnet_joana \
                    --name toph-node-1 \
                    --port 30333 \
                    --rpc-cors all \
                    --rpc-port 9933 \
                    --unsafe-ws-external \
                    --validator \
                    --ws-port 9944
          username: toph-node

            